version: "3.9"

services:
  train:
    container_name: experiment_training
    image: deep-rl-course:unit8-part2
    build: .
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - .:/workspace
    command: bash -c "huggingface-cli login && python3 train.py"
