version: "3.9"

services:
  training:
    container_name: experiment_training
    image: deep-rl-course:unit1
    build: .
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - .:/workspace
    command: python train.py
