defaults:
  - _self_
  - eval_env: pixelcopter_ple_v0

# Computing device
device: "gpu" # Options: "gpu" or "cpu"

# Tags for the model card in the Hub
tags:
  - "reinforce"
  - "reinforcement-learning"
  - "custom-implementation"
  - "deep-rl-class"

# Path to the directory of the training run to upload
model_dir: "runs/train/2023-01-10_06-19-53"
# Path to the trained model checkpoint
model_path : "${model_dir}/model.pt"
# Path to the hyperparameters used to train the model
hparams_path : "${model_dir}/hyperparameters.json"

# Name for the model file in the hub
model_name: "Reinforce_Pixelcopter-PLE-v0"

# Id of the repository in the Hugging Face Hub
# The format is: "{organization}/{repo_name}" (use your username as the "organization")
repo_id: "chavicoski/Reinforce_Pixelcopter-PLE-v0"

# Frames Per Second (fps) to use in the sample video of the repo
fps: 30

# Number of episodes to evaluate the model
eval_hparams:
  n_eval_episodes: 1000
  max_steps: 1000

hydra:
  run:
    dir: runs/model_to_hub/${now:%Y-%m-%d_%H-%M-%S}
