defaults:
  - _self_
  - env: frozen_lake_v1
  - train_hparams: default
  - eval_hparams: default

experiment_name: "QLearning_FrozenLake-v1-4x4-noSlippery"

hydra:
  run:
    # The experiment outputs will be stored in this folder
    dir: runs/train/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: True
